#!/bin/sh -ex

DB_NAME=drupal7
DB_USER=drupal7
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/drupal7

# install and setup drush
tar -zxf $SRC/drush-* -C /usr/local/share/
rm $SRC/drush-*

tar -zxf $SRC/Console_Table-* -C /usr/local/share/drush/lib/
rm $SRC/Console_Table-*

mkdir -p /etc/drush
cat > /etc/drush/drushrc.php << EOF
<?php
// by default use the drupal root directory
\$options['r'] = '$WEBROOT';
EOF

ln -s /usr/local/share/drush/drush /usr/local/bin/drush

# unpack drupal7 and configure
tar -zxf $SRC/drupal-*.tar.gz -C /var/www/
mv /var/www/drupal-* $WEBROOT
chown -R root:root $WEBROOT
chmod 640 $WEBROOT/*.txt
rm $SRC/drupal-*

mkdir -p $WEBROOT/sites/default/files
mkdir -p $WEBROOT/sites/default/files/styles
chown -R www-data:www-data $WEBROOT/sites/default/files

SETTINGS=$WEBROOT/sites/default/settings.php
cp $WEBROOT/sites/default/default.settings.php $SETTINGS
chown www-data:www-data $SETTINGS

/etc/init.d/mysql start
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"

# setup drupal via drush
drush site-install standard -y \
    --account-name=$ADMIN_NAME \
    --account-pass=$ADMIN_PASS \
    --site-name="TurnKey Drupal7" --db-su=root --db-su-pw=$MYSQL_PASS --db-url=mysql://$DB_USER:$DB_PASS@localhost/$DB_NAME

chown root:www-data $SETTINGS
chmod 640 $SETTINGS

# create welcome page
WELCOME='<p>Please follow these steps to set up and start using your website:</p><ol><li><strong>Configure your website:</strong> To get started, log in as <b>admin</b> and visit the <a href=\"/admin\">administration section</a>, where you can customize and configure all aspects of your website.</li><li><strong>Start posting content:</strong> When ready, delete this welcome and <a href=\"/node/add\">create content</a> for your website.</li></ol><p>For more information, please refer to the <a href=\"http://www.turnkeylinux.org/drupal7\">TurnKey Drupal7 release notes</a>, <a href=\"/admin/help\">help section</a>, or the <a href=\"http://drupal.org/handbooks\">online Drupal handbooks</a>. You may also post at the <a href=\"http://drupal.org/forum\">Drupal forum</a>, or view the wide range of <a href=\"http://drupal.org/support\">other support options</a> available.</p>'

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node VALUES ('1', '1', 'page', 'und', 'Welcome to TurnKey Drupal 7', '1', '1', '1334908018', '1334908036', '1', '1', '0', '0', '0');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_revision VALUES ('1', '1', '1', 'Welcome to TurnKey Drupal', '', '1334908036', '1', '1', '1', '0');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO field_data_body VALUES ('node', 'page', '0', '1', '1', 'und', '0', '$WELCOME', '$WELCOME', 'filtered_html');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO field_revision_body VALUES ('node', 'page', '0', '1', '1', 'und', '0', '$WELCOME', '$WELCOME', 'filtered_html');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_comment_statistics VALUES ('1', '0', '1334908036', '', '1', '0');"

# disable footer
$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE block SET region = '-1' WHERE delta = 'powered-by';"

/etc/init.d/mysql stop

