#!/bin/sh -ex

DB_NAME=drupal7
DB_USER=drupal7
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/drupal7

# set proxy settings
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

# increase php cli & apache memory limits (cli for drush)
sed -i "s|^memory_limit.*|memory_limit = 76M|" /etc/php/7.0/cli/php.ini
sed -i "s|^memory_limit.*|memory_limit = 64M|" /etc/php/7.0/apache2/php.ini

# install drush latest 7.x
git clone -b 7.x --depth 1 https://github.com/drush-ops/drush.git $SRC/drush
cd $SRC/drush
composer install
ln -s $SRC/drush/drush /usr/local/bin/drush
ln -s $SRC/drush/drush.complete.sh /etc/bash_completion.d/drush

mkdir -p /etc/drush
cat > /etc/drush/drushrc.php << EOF
<?php
// by default use the drupal root directory
\$options['r'] = '$WEBROOT';
EOF

# download latest drupal7 and install
drush dl drupal-7 --destination=$(dirname $WEBROOT)
mv $(dirname $WEBROOT)/drupal-7* $WEBROOT

SETTINGS=$WEBROOT/sites/default/settings.php
cp $WEBROOT/sites/default/default.settings.php $SETTINGS
chown www-data:www-data $SETTINGS

/etc/init.d/mysql start

drush site-install standard -y \
    --account-name=$ADMIN_NAME \
    --account-pass=$ADMIN_PASS \
    --site-name="TurnKey Drupal7" --db-su=root --db-su-pw=$MYSQL_PASS --db-url=mysql://$DB_USER:$DB_PASS@localhost/$DB_NAME

chown root:www-data $SETTINGS
chmod 640 $SETTINGS
chown -R www-data:www-data $WEBROOT/sites/default/files

# download, install and enable modules
drush dl --default-major=7 \
	admin_menu \
	admin_views \
	advanced_help \
	backup_migrate \
	ckeditor \
	colorbox \
	ctools \
	entity \
	field_group \
	globalredirect \
	google_analytics \
	honeypot \
	i18n \
	imce \
	libraries \
	module_filter \
	panels \
	pathauto \
	rules \
	token \
	variable \
	views \
	views_bulk_operations

drush en -y \
	actions_permissions \
	admin_menu \
	admin_menu_toolbar \
	admin_views \
	module_filter \
	ctools \
	advanced_help \
	backup_migrate \
	entity \
	pathauto \
	token \
	globalredirect \
	honeypot \
	googleanalytics \
	ckeditor \
	views \
	views_bulk_operations \
	views_ui

drush dis -y \
	toolbar

drush cc all

# configure D7 3rd party libraries path
LIBRARIES_PATH=$WEBROOT/sites/all/libraries
mkdir -p $LIBRARIES_PATH

# link jquery-colorbox for colorbox module
ln -s /usr/share/javascript/jquery-colorbox/ $LIBRARIES_PATH/colorbox

tar -zxf $SRC/ckeditor_*.tar.gz -C $LIBRARIES_PATH
rm -f $SRC/ckeditor_*.tar.gz

chown -R root:root $WEBROOT/sites/all

# disable poor mans cron and setup drush cron
cat >>$WEBROOT/sites/default/settings.php<< EOF

/**
 * Disable Poor Man's Cron:
 *
 * Drupal 7 enables the built-in Poor Man's Cron by default.
 * Poor Man's Cron relies on site activity to trigger Drupal's cron,
 * and is not well suited for low activity websites.
 *
 * We will use the Linux system cron and override Poor Man's Cron
 * by setting the cron_safe_threshold to 0.
 *
 * To re-enable Poor Man's Cron:
 *    Comment out (add a leading hash sign) the line below,
 *    and the system cron in /etc/cron.d/drupal7.
 */
\$conf['cron_safe_threshold'] = 0;
EOF

CRON_DRUPAL=/etc/cron.hourly/drupal7
cat >$CRON_DRUPAL<<EOF
#!/bin/bash -e
# Trigger drush cron
# Alternatively Drupal's poor mans cron: sites/default/settings.php

[ -x /usr/local/bin/drush ] || exit 0

su www-data -s /bin/bash -c "/usr/local/bin/drush --quiet cron"
EOF
chmod +x $CRON_DRUPAL

# create welcome page
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"

WELCOME='<p>Please follow these steps to set up and start using your website:</p><ol><li><strong>Configure your website:</strong> To get started, log in as <b>admin</b> and visit the <a href=\"/admin\">administration section</a>, where you can customize and configure all aspects of your website.</li><li><strong>Start posting content:</strong> When ready, delete this welcome and <a href=\"/node/add\">create content</a> for your website.</li></ol><p>For more information, please refer to the <a href=\"https://www.turnkeylinux.org/drupal7\">TurnKey Drupal7 release notes</a>, <a href=\"/admin/help\">help section</a>, or the <a href=\"http://drupal.org/handbooks\">online Drupal handbooks</a>. You may also post at the <a href=\"http://drupal.org/forum\">Drupal forum</a>, or view the wide range of <a href=\"http://drupal.org/support\">other support options</a> available.</p>'

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node VALUES ('1', '1', 'page', 'und', 'Welcome to TurnKey Drupal 7', '1', '1', '1334908018', '1334908036', '1', '1', '0', '0', '0');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_revision VALUES ('1', '1', '1', 'Welcome to TurnKey Drupal', '', '1334908036', '1', '1', '1', '0');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO field_data_body VALUES ('node', 'page', '0', '1', '1', 'und', '0', '$WELCOME', '$WELCOME', 'filtered_html');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO field_revision_body VALUES ('node', 'page', '0', '1', '1', 'und', '0', '$WELCOME', '$WELCOME', 'filtered_html');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_comment_statistics VALUES ('1', '0', '1334908036', '', '1', '0');"

# disable footer
$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE block SET region = '-1' WHERE delta = 'powered-by';"

/etc/init.d/mysql stop

# configure apache
a2dissite 000-default
a2ensite drupal7
a2enmod rewrite

# unset proxy settings
unset HTTP_PROXY

