#!/bin/bash -e

cd /var/www/drupal7
TMPFILE=$(mktemp)
trap "rm -f $TMPFILE" INT TERM EXIT
/usr/local/bin/drush pm-updatestatus --security-only > $TMPFILE

if grep -q 'SECURITY UPDATE' $TMPFILE; then
	cat $TMPFILE | mail -s 'Drupal security updates available' root
fi
